<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acccount registration at {sitename} ' => '',
    'Account registration at {sitename}' => '',
    'Contact us' => '',
    'E-mail' => '',
    'Incorrect username or password.' => '',
    'Log in' => '',
    'Login' => '',
    'Logout ({username})' => '',
    'New contact form request' => '',
    'Password' => '',
    'Password reset for {sitename}' => '',
    'Password reset token cannot be blank.' => '',
    'Remember me' => '',
    'Send it again' => '',
    'Send message' => '',
    'Send message to us' => '',
    'There is no user with this email address.' => '',
    'Verification code' => '',
    'Verify email token cannot be blank.' => '',
    'Wrong password reset token.' => '',
    'Wrong verify email token.' => '',
    'Your message' => '',
    'Your name' => '',
    'Your phone number' => '',
    'reset it' => '',
];
